version: 0.0
os: linux
files:
  - source: source
    destination: /var/www/html
  - source: config
    destination: /etc/nginx/
permissions:
  - object: /var/www
    mode: 755
    owner: nginx
    type:
      - directory
  - object: /var/www/html
    pattern: '**'
    mode: 644
    owner: nginx
hooks:
  ApplicationStop:
    - location: scripts/application-stop.sh
  BeforeInstall:
    - location: scripts/install-apache.sh
    - location: scripts/fix-nginx-conf.sh
  ApplicationStart:
    - location: scripts/application-start.sh
